# Generated by Django 4.2.6 on 2023-11-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uri_path',
            field=models.CharField(default='', max_length=120),
        ),
    ]
