# Generated by Django 4.2.6 on 2023-12-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20231212_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=60)),
                ('topic', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=13)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
